name             'chef-metal'
maintainer       'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license          'Apache 2.0'
description      'Provides a recipe for configuring the Chef Metal gem.'
long_description 'Provides a recipe for configuring the Chef Metal gem.'
version          '0.1.0'
